name: Release Firmware

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: "Release"
    strategy:
      fail-fast: true
    container: ghcr.io/qmk/qmk_cli
    runs-on: ubuntu-latest
    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Compile firmware
      run: qmk compile -kb splitkb/aurora/corne/rev1 -km samisagit -e CONVERT_TO=liatris

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.bin
          *.hex
          *.uf2
          .build/failed.*

